export const dynamic = 'force-dynamic';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TopNavbar from '@/components/HeaderParts/TopNavbar';
import BottomNavbar from '@/components/HeaderParts/BottomNavbar';
import Footer from '@/components/FooterParts/Footer';
import YoutubeVideoPopup from '@/components/YoutubeVideoPopup';
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ['latin'] });
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, unstable_setRequestLocale } from 'next-intl/server';
import { Locale, locales } from '@/i18config';
import HamburgerSidebarPopup from '@/components/HamburgerSidebarPopup';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Toaster richColors />
          <YoutubeVideoPopup />
          <TopNavbar locale={locale} />
          <BottomNavbar locale={locale} />
          <HamburgerSidebarPopup locale={locale} />
          {children}
          <Footer locale={locale} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
